name: Generate and Deploy Live File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight
    
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clean system cache
      run: |
        sudo apt-get clean
        sudo apt-get autoclean
        sudo apt-get autoremove

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run search_Tv.py
      run: |
          python from-m3u-to-txt.py
